spring:
  datasource:
    username: root
    password: 123
    url: jdbc:mysql://localhost:3306/springboot?serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    #开启自动创建表或更新
    hibernate:
      ddl-auto: update
    #开启打印sql语句
    show-sql: true